// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    setnx_pexpire: "local result = redis.call('SETNX', KEYS[1], ARGV[1])\nif result == 1 then\n  redis.call('PEXPIRE', KEYS[1], ARGV[2])\nend\nreturn result",
    delequal: "local deleted = 0\nfor i = 1, #KEYS, 1 do\n  if redis.call('GET', KEYS[i]) == ARGV[i] then\n    redis.call('DEL', KEYS[i])\n    deleted = deleted + 1\n  end\nend\nreturn deleted",
    zmembers: "local key = KEYS[1]\nlocal results = {}\n\nif redis.call('ZCARD', key) == 0 then\n  return {}\nend\n\nfor i = 1, #ARGV, 1 do\n  local memberName = ARGV[i]\n  if redis.call('ZSCORE', key, memberName) then\n    table.insert(results, memberName)\n  end\nend\n\nreturn results;",
    znotmembers: "local key = KEYS[1]\nlocal results = {}\n\nif redis.call('ZCARD', key) == 0 then\n  return ARGV\nend\n\nfor i = 1, #ARGV, 1 do\n  local memberName = ARGV[i]\n  if not redis.call('ZSCORE', key, memberName) then\n    table.insert(results, memberName)\n  end\nend\n\nreturn results;"
  };

}).call(this);
